kind: Template
apiVersion: v1
metadata:
  name: f8build
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    name: f8build
  type: Opaque
  data:
    db.host: ZGI=
    db.port: NTQzMg==
    db.user: cG9zdGdyZXM=
    db.password: bXlzZWNyZXRwYXNzd29yZA==
    sentry.dsn: c2VjcmV0
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: f8build
  type: Opaque
  data:
    postgres.sslmode: require
    postgres.connection.maxidle: "90"
    postgres.connection.maxopen: "90"
    environment: prod-preview
    auth.url: https://auth.prod-preview.openshift.io
